// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'MISSING_WEB_API_KEY',
        appId: dotenv.env['FIREBASE_APP_ID'] ?? 'MISSING_WEB_APP_ID',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'MISSING_SENDER_ID',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'hostelreservation-1defd',
        authDomain: '${dotenv.env['FIREBASE_PROJECT_ID'] ?? 'hostelreservation-1defd'}.firebaseapp.com',
        storageBucket: '${dotenv.env['FIREBASE_PROJECT_ID'] ?? 'hostelreservation-1defd'}.firebasestorage.app',
      );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtBA1E8z9GxGYZQ2b0T2JmmS8JcFZtjw',
    appId: '1:1053110957892:android:3f62ad94a8ad058499c911',
    messagingSenderId: '1053110957892',
    projectId: 'hostelreservation-1defd',
    storageBucket: 'hostelreservation-1defd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOezQy9yhjkRcG4cN6l7pY-Rhpd2YsrJQ',
    appId: '1:1053110957892:ios:ba555077fb32c3bd99c911',
    messagingSenderId: '1053110957892',
    projectId: 'hostelreservation-1defd',
    storageBucket: 'hostelreservation-1defd.firebasestorage.app',
    iosBundleId: 'com.example.hostelReservation',
  );
}
